requirements: Remove uvloop for compatibility in Windows
RuntimeError: uvloop does not support Windows at the moment
When execute command 'pip install uvloop', upper error occured